version: '3.8'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: athena
    container_name: athena-app
    restart: unless-stopped
    pull_policy: always
    working_dir: /var/www/html
    networks:
      - athena-network
    depends_on:
      - mysql
  nginx:
    image: nginx:alpine
    container_name: athena-nginx
    restart: unless-stopped
    ports:
      - "8000:80"  # Map port 8010 on the host to port 80 in the container
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - athena-network

  mysql:
    image: 'mysql:8.0.42'
    ports:
      - '3307:3306'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-Kang@2k25}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-Kang@2k25}'
    volumes:
      - 'sail-mysql:/var/lib/mysql/data'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - athena-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
networks:
  athena-network:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
