version: '3.8'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: athena-app
    restart: unless-stopped
    working_dir: /var/www/html
    networks:
      - athena-network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: 'mysql'
      DB_HOST: 'athena-mysql'
      DB_PORT: '3306'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'

  nginx:
    image: nginx:alpine
    container_name: athena-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d
    networks:
      - athena-network
    depends_on:
      - laravel.test
      - mysql

  mysql:
    image: 'mysql:8.0.42'
    container_name: athena-mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - athena-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s

networks:
  athena-network:
    driver: bridge

volumes:
  sail-mysql:
    driver: local