version: '3.8'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: athena-app
    restart: unless-stopped
    pull_policy: always
    working_dir: /var/www/html
    networks:
      - athena-network
    depends_on:
      - mysql
    # Remove the ports section here, as PHP-FPM doesn't need to be exposed.

  nginx:
    image: nginx:alpine
    container_name: athena-nginx
    restart: unless-stopped
    ports:
      - "8000:80" # This port is for your web application.
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - athena-network
    depends_on:
      - laravel.test
      - mysql

  mysql:
    image: 'mysql:8.0.42'
    container_name: athena-mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-Kang@2k25}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-Kang@2k25}'
    volumes:
      - 'sail-mysql:/var/lib/mysql/data'
    networks:
      - athena-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
      retries: 3
      timeout: 5s

networks:
  athena-network:
    driver: bridge

volumes:
  sail-mysql:
    driver: local